project_name: pinentry-touchid

before:
  hooks:
    - go mod download

builds:
  -
    main: ./main.go
    binary: pinentry-touchid
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'

# Generate/update a homebrew formula
brews:
  -
    tap:
      owner: jorgelbg
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"

    homepage: "https://github.com/jorgelbg/pinentry-touchid"

    caveats: |
      ➡️  Ensure that pinentry-mac is the default pinentry program:
            #{bin}/pinentry-touchid -fix

      ✅  Add the following line to your ~/.gnupg/gpg-agent.conf file:
            pinentry-program #{bin}/pinentry-touchid

      🔄  Then reload your gpg-agent:
            gpg-connect-agent reloadagent /bye

      🔑  Run the following command to disable "Save in Keychain" in pinentry-mac:
            defaults write org.gpgtools.common DisableKeychain -bool yes

      ⛔️  If you are upgrading from a previous version, you will be asked to give
          access again to the keychain entry. Click "Always Allow" after the
          Touch ID verification to prevent this dialog from showing.

    description: |
      Custom GPG pinentry program for macOS that allows using Touch ID for fetching the password from
      the macOS keychain.

    # Packages your package depends on.
    dependencies:
      - pinentry-mac
      - pinentry

    install: |
      bin.install "pinentry-touchid"

archives:
- replacements:
    darwin: macos

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^ci:'
    - '^dev:'
    - '^env:'
